language: php

php:
  - 7.0
  - 7.1
before_install:
  - sudo apt-add-repository ppa:dperry/ppa-graphviz-test -y
  - sudo apt-get update
  - sudo apt-get autoremove graphviz
  - sudo apt-get install graphviz

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
